# Generated by Qwen4 (direct vLLM)
# .env additions
VLLM_QWEN3_CODER_API_KEY="your-api-key-here"
VLLM_QWEN3_CODER_BASE_URL="https://cp937mgptqc1kp-8000.proxy.runpod.net/v1"

# llm_clients.py
from openai import OpenAI
from core.ai_provider import ProviderError

def call_qwen3_coder_text(prompt, model="Qwen3-Coder", **kwargs):
    base_url = "VLLM_QWEN3_CODER_BASE_URL"
    api_key = "VLLM_QWEN3_CODER_API_KEY"
    
    client = OpenAI(
        base_url=base_url,
        api_key=api_key
    )
    
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            **kwargs
        )
        return response.choices[0].message.content
    except Exception as e:
        raise ProviderError(f"Qwen3 Coder API error: {str(e)}")

# core/ai_provider.py
from urllib.request import Request, urlopen
from urllib.error import URLError

def check_qwen3_coder_available():
    base_url = "VLLM_QWEN3_CODER_BASE_URL"
    api_key = "VLLM_QWEN3_CODER_API_KEY"
    
    if not base_url or not api_key:
        return False
    
    try:
        req = Request(f"{base_url}/health")
        req.add_header("Authorization", f"Bearer {api_key}")
        urlopen(req, timeout=5)
        return True
    except URLError:
        return False

register_provider(
    name="qwen3_coder_text",
    func=call_qwen3_coder_text,
    cost_tier="paid",
    available_fn=check_qwen3_coder_available
)

# core/ai.py
from core.ai_provider import ROLE_PROVIDERS

# Insert after primary providers, before universal Claude
ROLE_PROVIDERS.append({
    "provider": "qwen3_coder_text",
    "roles": [role for role in TEXT_ROLES if role != "code"],
    "priority": 15  # Between primary providers (1-10) and Claude (20+)
})

# tests/test_ai_provider.py
import os
import pytest
from unittest.mock import patch
from core.ai_provider import check_qwen3_coder_available, ROLE_PROVIDERS

@patch.dict(os.environ, {
    "VLLM_QWEN3_CODER_API_KEY": "test-key",
    "VLLM_QWEN3_CODER_BASE_URL": "https://example.com"
})
@patch("urllib.request.urlopen")
def test_qwen3_coder_available(mock_urlopen):
    assert check_qwen3_coder_available() is True
    mock_urlopen.assert_called_once()

@patch.dict(os.environ, {
    "VLLM_QWEN3_CODER_API_KEY": "",
    "VLLM_QWEN3_CODER_BASE_URL": "https://example.com"
})
def test_qwen3_coder_unavailable():
    assert check_qwen3_coder_available() is False

def test_role_providers_order():
    qwen3_index = [p["provider"] for p in ROLE_PROVIDERS].index("qwen3_coder_text")
    assert qwen3_index > [p["provider"] for p in ROLE_PROVIDERS].index("anthropic")
    assert qwen3_index < [p["provider"] for p in ROLE_PROVIDERS].index("claude")

# tests/test_llm_clients.py
import pytest
from unittest.mock import patch
from llm_clients import call_qwen3_coder_text

@patch("openai.OpenAI")
def test_qwen3_coder_call(mock_client):
    mock_client.return_value.chat.completions.create.return_value.choices[0].message.content = "Test response"
    
    result = call_qwen3_coder_text("What is 2+2?")
    assert result == "Test response"
    
    mock_client.assert_called_with(
        base_url="VLLM_QWEN3_CODER_BASE_URL",
        api_key="VLLM_QWEN3_CODER_API_KEY"
    )

@patch.dict(os.environ, {
    "VLLM_QWEN3_CODER_API_KEY": "",
    "VLLM_QWEN3_CODER_BASE_URL": ""
})
def test_qwen3_coder_missing_env():
    with pytest.raises(ValueError):
        call_qwen3_coder_text("What is 2+2?")