# Generated by Qwen4 (direct vLLM)
import unittest
from abc import ABC, abstractmethod
from enum import Enum
from typing import Dict, Any, Optional, List
import threading

# ----------------------------
# Core Components
# ----------------------------

class Department(Enum):
    PLANNER = "planner"
    ARCHITECT = "architect"
    ENGINEER = "engineer"
    RESEARCHER = "researcher"
    SECURITY = "security"
    QA = "qa"
    REVIEWER = "reviewer"
    LEGAL = "legal"
    FINANCE = "finance"
    OPERATIONS = "operations"
    DOCUMENTATION = "documentation"
    KNOWLEDGE = "knowledge"
    REFLECTION = "reflection"
    PREDICTION = "prediction"
    LEARNING = "learning"

class TaskStatus(Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"

class KnowledgeGraph:
    def __init__(self):
        self._store = {}
        self._lock = threading.Lock()
    
    def get(self, key: str) -> Any:
        with self._lock:
            return self._store.get(key)
    
    def set(self, key: str, value: Any) -> None:
        with self._lock:
            self._store[key] = value
    
    def delete(self, key: str) -> None:
        with self._lock:
            if key in self._store:
                del self._store[key]

class BaseDepartment(ABC):
    def __init__(self, knowledge_graph: KnowledgeGraph):
        self.knowledge_graph = knowledge_graph
    
    @abstractmethod
    def process_task(self, task: Dict[str, Any]) -> Dict[str, Any]:
        pass

# ----------------------------
# Department Implementations
# ----------------------------

class Planner(BaseDepartment):
    def process_task(self, task: Dict[str, Any]) -> Dict[str, Any]:
        # Example: Break down high-level tasks into subtasks
        result = {
            "action": "task_decomposition",
            "subtasks": [f"subtask_{i}" for i in range(3)],
            "status": TaskStatus.COMPLETED
        }
        self.knowledge_graph.set(f"planner_{task['id']}", result)
        return result

class Architect(BaseDepartment):
    def process_task(self, task: Dict[str, Any]) -> Dict[str, Any]:
        # Example: Create system design documents
        result = {
            "action": "system_design",
            "design": "modular_microservices_architecture",
            "status": TaskStatus.COMPLETED
        }
        self.knowledge_graph.set(f"architect_{task['id']}", result)
        return result

class Engineer(BaseDepartment):
    def process_task(self, task: Dict[str, Any]) -> Dict[str, Any]:
        # Example: Generate code implementations
        result = {
            "action": "code_generation",
            "output": "def sample_function():\n    return 'Hello World'",
            "status": TaskStatus.COMPLETED
        }
        self.knowledge_graph.set(f"engineer_{task['id']}", result)
        return result

class QA(BaseDepartment):
    def process_task(self, task: Dict[str, Any]) -> Dict[str, Any]:
        # Example: Validate outputs
        result = {
            "action": "validation",
            "test_results": "all_tests_passed",
            "status": TaskStatus.COMPLETED
        }
        self.knowledge_graph.set(f"qa_{task['id']}", result)
        return result

# ----------------------------
# Kai Orchestration Engine
# ----------------------------

class Kai:
    def __init__(self):
        self.knowledge_graph = KnowledgeGraph()
        self.departments: Dict[Department, BaseDepartment] = {
            Department.PLANNER: Planner(self.knowledge_graph),
            Department.ARCHITECT: Architect(self.knowledge_graph),
            Department.ENGINEER: Engineer(self.knowledge_graph),
            Department.QA: QA(self.knowledge_graph)
        }
        self.task_history: List[Dict[str, Any]] = []
    
    def assign_task(self, task: Dict[str, Any]) -> Dict[str, Any]:
        department = self._determine_responsible_department(task)
        task["status"] = TaskStatus.IN_PROGRESS
        task["assigned_to"] = department.value
        self.task_history.append(task)
        
        result = self.departments[department].process_task(task)
        task["status"] = TaskStatus.COMPLETED
        task["result"] = result
        return task
    
    def _determine_responsible_department(self, task: Dict[str, Any]) -> Department:
        # Simple routing logic based on task type
        if task.get("type") == "planning":
            return Department.PLANNER
        elif task.get("type") == "design":
            return Department.ARCHITECT
        elif task.get("type") == "implementation":
            return Department.ENGINEER
        elif task.get("type") == "validation":
            return Department.QA
        else:
            return Department.PLANNER  # Default
    
    def self_modify(self, modification: Dict[str, Any]) -> None:
        # Example self-modification: Add new department
        if modification.get("action") == "add_department":
            department_type = modification["department_type"]
            department_class = modification["department_class"]
            self.departments[department_type] = department_class(self.knowledge_graph)

# ----------------------------
# Tests
# ----------------------------

class TestAIWorkforce(unittest.TestCase):
    def setUp(self):
        self.knowledge_graph = KnowledgeGraph()
        self.kai = Kai()
    
    def test_planner_task_decomposition(self):
        task = {"id": "T001", "type": "planning", "description": "Design system architecture"}
        result = self.kai.assign_task(task)
        
        self.assertEqual(result["assigned_to"], Department.PLANNER.value)
        self.assertEqual(result["status"], TaskStatus.COMPLETED)
        self.assertIn("subtasks", result["result"])
        self.assertEqual(len(result["result"]["subtasks"]), 3)
        self.assertEqual(self.kai.knowledge_graph.get(f"planner_{task['id']}"), result["result"])
    
    def test_architect_system_design(self):
        task = {"id": "T002", "type": "design", "description": "Create API architecture"}
        result = self.kai.assign_task(task)
        
        self.assertEqual(result["assigned_to"], Department.ARCHITECT.value)
        self.assertEqual(result["status"], TaskStatus.COMPLETED)
        self.assertEqual(result["result"]["design"], "modular_microservices_architecture")
        self.assertEqual(self.kai.knowledge_graph.get(f"architect_{task['id']}"), result["result"])
    
    def test_engineer_code_generation(self):
        task = {"id": "T003", "type": "implementation", "description": "Generate sample code"}
        result = self.kai.assign_task(task)
        
        self.assertEqual(result["assigned_to"], Department.ENGINEER.value)
        self.assertEqual(result["status"], TaskStatus.COMPLETED)
        self.assertIn("def sample_function()", result["result"]["output"])
        self.assertEqual(self.kai.knowledge_graph.get(f"engineer_{task['id']}"), result["result"])
    
    def test_qa_validation(self):
        task = {"id": "T004", "type": "validation", "description": "Test generated code"}
        result = self.kai.assign_task(task)
        
        self.assertEqual(result["assigned_to"], Department.QA.value)
        self.assertEqual(result["status"], TaskStatus.COMPLETED)
        self.assertEqual(result["result"]["test_results"], "all_tests_passed")
        self.assertEqual(self.kai.knowledge_graph.get(f"qa_{task['id']}"), result["result"])
    
    def test_kai_self_modification(self):
        # Test adding a new department
        class TestDepartment(BaseDepartment):
            def process_task(self, task: Dict[str, Any]) -> Dict[str, Any]:
                return {"action": "test", "status": TaskStatus.COMPLETED}
        
        modification = {
            "action": "add_department",
            "department_type": Department.RESEARCHER,
            "department_class": TestDepartment
        }
        
        self.kai.self_modify(modification)
        self.assertIn(Department.RESEARCHER, self.kai.departments)
        task = {"id": "T005", "type": "research", "description": "Conduct analysis"}
        result = self.kai.assign_task(task)
        self.assertEqual(result["assigned_to"], Department.RESEARCHER.value)

if __name__ == "__main__":
    unittest.main()