-- KAI Media Revenue Factory — indexes (migration 002)
CREATE INDEX IF NOT EXISTS idx_accounts_platform       ON accounts (platform_id);
CREATE INDEX IF NOT EXISTS idx_trends_status_score      ON trends (status, score DESC);
CREATE INDEX IF NOT EXISTS idx_trends_source           ON trends (source, fetched_at DESC);
CREATE INDEX IF NOT EXISTS idx_opportunities_factory    ON opportunities (factory_key, score DESC);
CREATE INDEX IF NOT EXISTS idx_opportunities_trend      ON opportunities (trend_id);
CREATE INDEX IF NOT EXISTS idx_content_factory_state    ON content (factory_key, state);
CREATE INDEX IF NOT EXISTS idx_content_status           ON content (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ideas_content            ON ideas (content_id);
CREATE INDEX IF NOT EXISTS idx_scripts_content          ON scripts (content_id);
CREATE INDEX IF NOT EXISTS idx_characters_universe      ON characters (universe_id);
CREATE INDEX IF NOT EXISTS idx_episodes_universe        ON episodes (universe_id);
CREATE INDEX IF NOT EXISTS idx_canon_universe           ON canon (universe_id);
CREATE INDEX IF NOT EXISTS idx_assets_content           ON assets (content_id);
CREATE INDEX IF NOT EXISTS idx_assets_sha256            ON assets (sha256);
CREATE INDEX IF NOT EXISTS idx_asset_lineage_asset      ON asset_lineage (asset_id);
CREATE INDEX IF NOT EXISTS idx_rights_asset             ON rights (asset_id);
CREATE INDEX IF NOT EXISTS idx_rights_content           ON rights (content_id);
CREATE INDEX IF NOT EXISTS idx_provenance_subject       ON provenance (subject_type, subject_id);
CREATE INDEX IF NOT EXISTS idx_publishing_content       ON publishing_jobs (content_id);
CREATE INDEX IF NOT EXISTS idx_publishing_status_mode   ON publishing_jobs (status, mode);
CREATE INDEX IF NOT EXISTS idx_analytics_content_metric ON analytics (content_id, metric);
CREATE INDEX IF NOT EXISTS idx_analytics_observed       ON analytics (observed_at DESC);
CREATE INDEX IF NOT EXISTS idx_patterns_state           ON patterns (state);
CREATE INDEX IF NOT EXISTS idx_pattern_lifecycle_pat    ON pattern_lifecycle (pattern_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_strategy_active          ON strategy_versions (active) WHERE active;
CREATE INDEX IF NOT EXISTS idx_failures_subject         ON failures (subject_type, subject_id);
CREATE INDEX IF NOT EXISTS idx_revenue_content          ON revenue (content_id);
CREATE INDEX IF NOT EXISTS idx_revenue_occurred         ON revenue (occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_costs_content            ON costs (content_id);
CREATE INDEX IF NOT EXISTS idx_media_events_cycle       ON media_events (cycle_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_media_audit_created      ON media_audit_events (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_media_audit_entity       ON media_audit_events (entity_type, entity_id);
