"""Tests for core/second_brain/types.py."""
from __future__ import annotations

import uuid

import pytest

from core.second_brain.types import (
    MEMORY_TYPE_STORE,
    ChangeType,
    Confidence,
    MemoryType,
    MergePolicy,
    QueryRequest,
    QueryResult,
    SecondBrainRecord,
    SourceAuthority,
)


class TestMemoryType:
    """Verify all 16 MemoryType values exist."""

    def test_all_16_values_exist(self):
        values = {e.value for e in MemoryType}
        assert len(values) == 16

    def test_expected_values(self):
        expected = {
            "INFRASTRUCTURE",
            "INCIDENT",
            "OPERATIONAL",
            "DECISION",
            "SEMANTIC",
            "EPISODIC",
            "TEMPORAL",
            "CONVERSATION",
            "WORKING_MEMORY",
            "SHORT_TERM",
            "PROJECT",
            "BUSINESS",
            "PERSONAL_CONTEXT",
            "RELATIONSHIP",
            "DOCUMENT",
            "PROCEDURAL",
        }
        assert {e.value for e in MemoryType} == expected


class TestChangeType:
    def test_all_8_values_exist(self):
        values = {e.value for e in ChangeType}
        assert len(values) == 8
        assert {"CREATED", "UPDATED", "DEGRADED", "RECOVERED", "DELETED", "MIGRATED", "ROTATED", "ESCALATED"} == values


class TestConfidence:
    def test_all_4_values_exist(self):
        values = {e.value for e in Confidence}
        assert len(values) == 4
        assert {"CONFIRMED", "DOCUMENTED", "CONVERSATIONAL", "INFERRED"} == values


class TestSourceAuthority:
    def test_all_7_tiers_exist(self):
        values = {e.value for e in SourceAuthority}
        assert len(values) == 7
        assert {1, 2, 3, 4, 5, 6, 7} == values


class TestMergePolicy:
    def test_all_3_values_exist(self):
        values = {e.value for e in MergePolicy}
        assert len(values) == 3
        assert {"NEWEST_WINS", "SOURCE_AUTHORITY", "UNION_ALL"} == values


class TestMemoryTypeStore:
    """Verify MEMORY_TYPE_STORE maps all 16 memory types."""

    def test_all_memory_types_covered(self):
        for mt in MemoryType:
            assert mt in MEMORY_TYPE_STORE, f"{mt} not in MEMORY_TYPE_STORE"

    def test_store_names(self):
        store_names = {v[0] for v in MEMORY_TYPE_STORE.values()}
        assert store_names == {"operational", "cognitive", "conversational", "project", "relationship"}


class TestSecondBrainRecord:
    def test_autogenerated_id_is_valid_uuid(self):
        record = SecondBrainRecord()
        assert record.id is not None
        uuid.UUID(record.id)  # raises if invalid

    def test_autogenerated_timestamp_is_iso_format(self):
        record = SecondBrainRecord()
        # Should parse without raising
        from datetime import datetime
        dt = datetime.fromisoformat(record.timestamp)
        assert dt.tzinfo is not None  # must be timezone-aware

    def test_to_dict_serializes_enums_to_strings(self):
        record = SecondBrainRecord()
        d = record.to_dict()
        assert isinstance(d["memory_type"], str)
        assert isinstance(d["change_type"], str)
        assert isinstance(d["confidence"], str)
        assert isinstance(d["source_authority"], int)

    def test_from_dict_roundtrips(self):
        original = SecondBrainRecord(
            entity="test-entity",
            entity_type="host",
            memory_type=MemoryType.INFRASTRUCTURE,
            fact={"ip": "192.168.1.1"},
            change_type=ChangeType.CREATED,
            confidence=Confidence.CONFIRMED,
            source_authority=SourceAuthority.LIVE_SYSTEM,
        )
        d = original.to_dict()
        restored = SecondBrainRecord.from_dict(d)
        assert restored.id == original.id
        assert restored.entity == original.entity
        assert restored.entity_type == original.entity_type
        assert restored.memory_type == original.memory_type
        assert restored.fact == original.fact
        assert restored.change_type == original.change_type
        assert restored.confidence == original.confidence
        assert restored.source_authority == original.source_authority
        assert restored.timestamp == original.timestamp

    def test_from_dict_with_string_source_authority(self):
        # SourceAuthority is an int Enum; from_dict should handle it
        d = {
            "id": str(uuid.uuid4()),
            "entity": "test",
            "entity_type": None,
            "memory_type": "OPERATIONAL",
            "fact": {},
            "change_type": "CREATED",
            "changed_reason": "",
            "confidence": "CONFIRMED",
            "source_authority": 1,
            "supersedes": None,
            "superseded_by": None,
            "timestamp": "2026-01-01T00:00:00+00:00",
            "ttl_seconds": None,
            "metadata": {},
        }
        record = SecondBrainRecord.from_dict(d)
        assert record.source_authority == SourceAuthority.LIVE_SYSTEM


class TestQueryRequest:
    def test_defaults(self):
        qr = QueryRequest()
        assert qr.entity is None
        assert qr.memory_types is None
        assert qr.time_range is None
        assert qr.require_confirmation is False
        assert qr.limit == 100


class TestQueryResult:
    def test_defaults(self):
        qr = QueryResult(records=[])
        assert qr.records == []
        assert qr.store == ""
        assert qr.merge_policy == MergePolicy.NEWEST_WINS
